### ISSUE TITLE
მთავარ გვერდზე კარუსელში ლინკის შეცვლა იგვიანებს

### ISSUE THREAD

**Issue by bakurits** [Girchi/girchi-com-ui#110]
![Screenshot from 2019-10-02 12-37-51](https://user-images.githubusercontent.com/10448754/66030033-8def8480-e511-11e9-9e46-71c5d3c832ad.png)
როცა ახალ სტატიაზე გადადის, სურათი იცვლება მაგრამ ლინკი რამდენიმე წამით აგვიანებს და დაჭერისას ისევ ძველზე გადადის

**Comment by Babunashvili** [comment]
1 2 წამი უნდა აცადო ანიმაცია არის ეგეთი FadeIn. ძველი სლაიდი გადის და ახალი შემოდის. სლაიდერის შემოსვლისთანავე ეგრევე თუ აწვები შეიძლება ახალი სლაიდის ანიმაცია არიყოს მორჩენილი მაგ დროს და მაგიტო ეკილება ძველს. ფოტოც არიქნება ბოლომდე შემოსული მაგ დროს. ასე რომ ეს არარი ბაგი
