### ISSUE TITLE
Hover effects

### ISSUE THREAD

**Issue by david-babunashvili** [Girchi/girchi-com-ui#12]
რამდენიმე ელემენტზე არ გვაქ დახატული როგორი უნდა იყოს მაუსის მიტანისას.

1. ![image](https://user-images.githubusercontent.com/8989712/56219151-4d8d6e80-6077-11e9-8ebf-67fea44b15a6.png)
2. ![image](https://user-images.githubusercontent.com/8989712/56219196-5d0cb780-6077-11e9-8240-e1cbd9051349.png)
3. ![image](https://user-images.githubusercontent.com/8989712/56219360-a8bf6100-6077-11e9-8315-1cffce55acc8.png)

**Comment by sandroob** [comment]
Other-ში ავტვირთე ზეპლინზე ეს ჰოვერები ^^

**Comment by david-babunashvili** [comment]
@sandroob სოციალურ აიკონებს რა ვუყო ფუტერში?
