### ISSUE TITLE
ნოტიფიკაციების მარკაპი

### ISSUE THREAD

**Issue by IliaNoz** [Girchi/girchi-com-ui#135]
დიზაინის მიხედვით დაიწერება ფრონტის სამუშაოები

**Comment by Ninchoo** [comment]
ეს არის დიზაინის ლინკი:

- [ ] გვაქვს ნოტიფიკაციები ზარზე რაოდენობის აღმნიშველით

- [ ] ზარზე დაჭერისას უნდა გაიხსნას ნოტფიკაციების სიის ჩამოშლა, სადაც ჩამოიშლება 10 შეტყობინება

- [ ] შეტყობინებების ჩამოშლილ სიას აქვს, მეტის ნახვის ღილაკი.

- [ ] მეტის ნახვის ღილაკზე დაჭერისას გადავდივართ ახალ გვერდზე სადაც იქნება ყველა ნოტიფიკაცია - infinite scroll

- [ ]  ნანახი შეტყობინება უნდა განსხვავდება ახლისგან

დესკტოპ ვერსია:
https://www.figma.com/proto/ta1YmEoqooKoJCqus6IA6D/Girchi?node-id=5%3A0&viewport=355%2C349%2C0.125&scaling=min-zoom&fbclid=IwAR35fRMhlsZ84QkqmlAFU0jln6CRnOeKcTVCF3dq8dePv5rcC9sYqqq2NyI

მობილური ვერსია:
https://www.figma.com/proto/ta1YmEoqooKoJCqus6IA6D/Girchi?node-id=335%3A0&viewport=717%2C4047%2C0.42991071939468384&scaling=min-zoom&fbclid=IwAR1258ZKWg1ZMZHomzHbCXsl03SjmTibLMW5ZSH1KCVo9YSY4EKgVhTBo20
