### ISSUE TITLE
Input design

### ISSUE THREAD

**Issue by david-babunashvili** [Girchi/girchi-com-ui#17]
მოკლედ ინფუთებზე მაქვს 2 ასეთი ქეისი

1. ეს ჩექმარქი ვერ მივხვდი როგორ უნდა მუშაობდეს ანუ რაც სქრინზეა უკვე საქსესია თუ რა არის? ან ერორის დროს როგორ უნდა იყოს და ერორ მესიჯი როგორ უნდა გამოდიოდეს?

2. ეს არის ინფუთის placeholder რომელსაც ტექნიკურად არ აქვს ლაინბრეიქის საშუალება.

![image](https://user-images.githubusercontent.com/8989712/56355997-c102bd80-61e8-11e9-8993-e37099acc444.png)

**Comment by sandroob** [comment]
1. კი რაც სქრინზეა უკვე success-ია და ერორი User Side - Account-ში შეგიძლია ნახო თავისი "ჰინტით"
![image](https://user-images.githubusercontent.com/49644905/56385038-0c3fbf00-622f-11e9-863e-096c4de32218.png)

**Comment by sandroob** [comment]
2. თუ მასე არ გამოდის როგორც მანდაა, მაშინ ეგ"მიუთითეთ ესა და ეს" ავიტანოთ ზემოთ ტექსტში და ეგ ცარიელი დავტოვოთ

**Comment by shavidzet** [comment]
@david-babunashvili 

>     2. ეს არის ინფუთის placeholder რომელსაც ტექნიკურად არ აქვს ლაინბრეიქის საშუალება.

textarea ელემენტით ვფიქრობ მოგვარებადია ეს პრობლემა
