### ISSUE TITLE
UX improvement

### ISSUE THREAD

**Issue by david-babunashvili** [Girchi/girchi-com-ui#18]

**Comment by david-babunashvili** [comment]
ლოგინის გევრდზე რომ გვაქ ეს სექცია რატომ არ გვაქ იგივე რეგისტრაცის გვერდზე? ანუ თუ ლოგინიდან უცებ გადადიხარ რეგისტრაცუაზე რეგისტრაციდან ლოგინზე რატომ არა?

![image](https://user-images.githubusercontent.com/8989712/56356265-674ec300-61e9-11e9-8a3f-f7f63c8eeb97.png)
![image](https://user-images.githubusercontent.com/8989712/56356280-73d31b80-61e9-11e9-814b-4c4b4f5b90de.png)

**Comment by sandroob** [comment]
ანუ იდეაში შესვლის გვერდიდან უფრო შეიძლება ტიპი გადავიდეს რეგისტრაციის გვერდზე ვიდრე პირიქით. უკვე დარეგისტრირებული ტიპი აღარ შევა მაგ გვერდზე, თუ შემთხვევით მოხვდა, ქვემოთ არ ჩამოსქროლავს შესვლის გვერდზე გადასასვლელი ლინკი რომ იპოვოს, იქვე აქვს ჰედერში. ვინც მაგ ინპუტებს შეავსებს და ჩამოსქროლავს იმას კიდევ არამგონია შესვლის გვერდი სჭირდებოდეს. ანუ იდეაში გავაპრავე, თუმცა რავი თუ საჭიროა ან სხვა ლოგიკაა, ჩავსვავ მასეთივე ბლოკს, არაა პრობლემა მამენტ :d
