### ISSUE TITLE
Project Setup Suggestions

### ISSUE THREAD

**Issue by thecotne** [Girchi/girchi-com-ui#2]
ჩემს რეკომენდაციებს გაგიზიარებთ როგორ ჯობია პროექტის მოწყობა

- [x] სხვისი კოდი არ უნდა იყოს რეპოზიტორიაში (უნდა დაყენდეს პაკეტ მენეჯერით, bootstrap არის გასატანი ანუ)
- [x] რეპოზიტორიაში უნდა იყოს პაკეტ მენეჯერის lock ფაილი (`package-lock.json` npm ის შემთხვევაში ან `yarn.lock` yarn ის შემთხვევაში)
- [x] ბევრ რამეში yarn ისევ ჯობია npm ს და გირჩევთ yarn ის გამოყენებას
- [x] `package.json` ში უნდა იყოს [engines](https://docs.npmjs.com/files/package.json#engines) ფილდი და უნდა მოვითხოვოთ node, npm (yarn თუ yarn ს გამოვიყენებთ) ბოლო LTS ან stable ვერსია (რომ მერე არ იყოს ჩემთან მუშაობს ინსტალი და შენთან რატო არ ეშვება?!)
- [x] `package.json` იდან ამოსაღებია ზედმეტი ფილდები რომლებიც არაა საჭირო პაკეტებისთვის რომელიც არის `"private": true,` და არ ფაბლიშდება npm ზე name, version, description, repository, keywords, license
- [x] პაკეტებისთვის რომლებიც არის `"private": true,` არ არსებობს განსხვავება `devDependencies` სა და `dependencies` შორის და მე გირჩევთ რომ ყველაფერი იყოს `dependencies` ში 
- [x] გირჩევთ გამოიყენოთ [eslint](https://eslint.org/) js ისთვის და [prettier](https://prettier.io/) html/scss ისთვის
  - [x] eslint ისთვის გირჩევთ [standardjs](https://standardjs.com/) ის კონფიგს [eslint-config-standard](https://github.com/standard/eslint-config-standard) 

ესე გამოიყურება ხოლმე ჩემი `package.json` (მეტი ფილდები არაა საჭირო)

```json
{
  "private": true,
  "version": "0.0.0-not-versioned",
  "license": "UNLICENSED",
  "engines": {
    "node": "^10.15.0",
    "npm": "^6.7.0",
    "yarn": "^1.13.0"
  },
  "scripts": {
  },
  "dependencies": {
  }
}
```

---

follow up of https://github.com/Girchi/girchi-com-ui/pull/1#issuecomment-481128673

**Comment by otarza** [comment]
@thecotne დიდი მადლობა <3

ყველაფერს გავითვალისწინებთ და შემდეგ კიდევ ერთ რევიუს გთხოვთ თუ დრო გექნება.

cc: @david-babunashvili

**Comment by thecotne** [comment]
@otarza არა რისი მადლობა კაცო ...

მე ვიყავი პირველად ვინც თქვა გირჩის პროექტები open source იყოსო და მიტყდება რო მეთვითონ ვერ მოვიცალე დეველოპმენტისთვის მაგრამ მაინც ვცდილობ რო თქვენთან ვიყო (შორიახლოს :D )

თუ რამე დაგჭირდეთ ან რამე გაუგებრად დავწერე მკითხეთ (github ყველაფერს ვკითხულობ fb სგან განსხვავებით :) )

**Comment by otarza** [comment]
@thecotne ❤️

აუცილებლად შეგაწუხებთ, რაც კი გირჩისთვის დაიწერება ყველაფერი ოფენ-სორსი იქნება ამ პროექტის ფარფლებში როგორც მინიმუმ. იქნებ შევკრიბოთ ქომუნითი ან ყველაფრის ირგვლივ.

**Comment by thecotne** [comment]
აქვე გირჩევთ რომ master, develop ზე მერჯები რევიუს გარეშე და push ები გათიშოთ (push ებს მე owner ებსაც ვუთიშავ ხოლმე gitlab ზე და github ზე როგორაა არ მახსოვს)

თორე ძაან მარტივია git flow დან გადახვევა და არაა კარგი...

**Comment by otarza** [comment]
@thecotne done!

**Comment by david-babunashvili** [comment]
@thecotne კი თუ გლობალურად აყენია. მაგრამ eslint-ზე მქონდ ასეთი ქეისი რომ "extends": "standard", standard-ს ვერ ხედავდა რადგან eslint გლობალურად მეყენა და ეს ფექიჯი ლოკალურად ამიტო ესლინტი ლოკალურად გამოვიძახე ნიუდ მოდულებიდან. იმის დაყენებაც შეილებოდა მამენტ გლობალურად მაგრამ ეს eslint და prettier ყველას შეილება არეყენოს გლობალურად და მაგიტო ვიფიქრე ლოკალურად გამოძახება.

**Comment by thecotne** [comment]
@david-babunashvili გლობალურად არაფერი არ დააყენო არც webpack არც eslint etc.

და npm/yarn სკრიპტს რო უშვებს path ში გიმატებს `./node_modules/.bin` ს და მაგის მიწერა აღარ ჭირდება

---

Related Docs: https://docs.npmjs.com/misc/scripts#path

**Comment by david-babunashvili** [comment]
@thecotne აჰა გასაგებია

**Comment by thecotne** [comment]
სუ ეგ იყო

---

Related PR https://github.com/Girchi/girchi-com-ui/pull/4
