### ISSUE TITLE
CI/CD tool integration

### ISSUE THREAD

**Issue by shavidzet** [Girchi/girchi-com-ui#22]
ვფქირობ, რომ თანამედროვე ვებ-აპპებში აუცილებელია CI/CD, მინიმუმ ლინტი მაინც უნდა ეშვებოდეს და დეველოპმენტ რელიზები უნდა დადეპლოვდეს, რათა გამარტივდეს ui ტესტირებები და კოდის ბრაუზერამდე სწრაფად მიტანა.

რეკომენდაციას ვუწევ https://www.netlify.com/
5 წუთში შესაძლებელია multi branch deployment-ის აწყობა და ნოტიფიკაციების ინტეგრაცია.

**Comment by jibla** [comment]
დეველოპმენტ რელიზების დიფლოიმენტი ხდება ავტომატურად ომედიას Jenkins ჯობით http://ui.girchi.com-ზე. აქ მიდის ყველა PR და ნებისმიერი push, develop ბრენჩში.

ლინტის გაშვებაც შეგვიძლია.

\cc @otarza

**Comment by shavidzet** [comment]
@jibla ასწორებს ✌️ 

მაშინ ალბათ სჯობს რო სადმე იყოს ეს ინფო

**Comment by thecotne** [comment]
მეც დავწერ ორ სიტყვას ამ საკითხზე

- როგორც ჩანს web hook ებით ან ხელით ათრიგერებთ დეპლოის (რაც არაა სწორი)
  - github ზე არ ჩანს რო იბილდება და დეპლოვდება რამე
  - ასევე არ ჩანს სტატუსი (ბილდის, ლინტის, ან/და სხვა რაიმე ტესტების)
  - არ ჩანს PR ს დომენი სადაა (თუ დეპლოვდება ცალკე დომენზე PR ები)
- ასევე CI/CD წესით არის პროექტის ნაწილი და ამის კონფიგურაცია რომ სადღაც ვიღაცის Jenkins შია არაა სწორი
  - მითუმეტეს რომ open source პროექტებისთვის ყველა CI/CD სოლუშენი უფასოა

**Comment by jibla** [comment]
@thecotne @shavidzet 
გეთანხმებით ორივეს.

სწრაფად ავაწყეთ ეს, რომ საშუალება გვქონოდა მუდმივად განახლებული ვერსია სადმე გვენახა.

ვეცდებით, რომ მალე გამოვნახოთ რესურსი სრულფასოვანი CI/CD-ის ასაწყობად

**Comment by jibla** [comment]
ან, თუ თქვენ დაგვეხმარებით, ძალიან ღირებული კონტრიბუცია იქება  :D  <3

**Comment by thecotne** [comment]
@shavidzet netlify ს ქომაგი შენ ხარ (მე ჯერ არსად არ გამომიყენებია)

და დააყენე თუ არ დაგეზარება (CI თუ არ აქვს მაგას travis ზე ავწიოთ girchi ს ანგარიში)

სადაც დაგჭირდება girchi ს ანგარიში დაარეგისტრირე და მერე საზეიმო ვითარებაში გადავცეთ ვიზეც იტყვიან იმას

**Comment by jibla** [comment]
@shavidzet @thecotne 
აპლიკაციის ნაწილში, ვგეგმავთ რომ travis გამოვიყენოთ (რადგან ყველაფერი public არის, უფასოც გვექნება). ამიტომ, შეიძლება, ლოგიკური იყოს ესეც ტრევისით გაკეთდეს ბარემ.

**Comment by shavidzet** [comment]
@thecotne CI აქვს მარა ფაიფლაინების მენეჯმენტი და რაღაც-რუღაცეები არ აქვს...

@jibla ტრევისთან გითჰაბი მეგობრობს მამენტ და ეგ რაღაცეების ინტეგრაციას ამარტივებს გზაზე.

კონფიგი მე ძაან მარტივად მესახება:
* lint
* test
* build
* delivery

ახლა ტასკის შესრულებას რაც შეეხება მე სურვილი მაქვს მუშაობის, მაგრამ დრო არ მაქვს ამჟამად, თუ სხვა მსურველია ვინმე დაე გააკეთოს, თუ არა და დაიკიდეთ ცოტახნით და მე გამოვუშვებ PR-ს უახლოეს კვირებში 😄

**Comment by thecotne** [comment]
მე ვიზამ საღამოს

(იმედია ტრევისიდან netlify ზე deploy მოსულა)

**Comment by shavidzet** [comment]
<img src="https://cdn.netlify.com/51b3c2b9b2cb2eb70fd9631385a2b0d2bc60b1ea/b89b5/img/docs/webhooks/incoming.png"> - გათვალისწინებულია ეგ იდეა 👍 

სტატიაშიც ახსნილია დეტალურად: https://therocketeers.github.io/blog/using-travis-ci-to-deploy-jekyll-on-netlify/

**Comment by thecotne** [comment]
netlify ზე Open Source Plan მინდა რო ავიღო და ლიცენზია უნდა გქონდეთ შესაბამისიო და ჩვენი ლინკი ჩააგდეთ საიტზეო და რას იტყვით?

https://www.netlify.com/legal/open-source-policy/

**Comment by shavidzet** [comment]
თუ ჯერ არაა გაკეთებული, PR რო მიიმერჯება ნეტლიფაის ბოტმა უნდა დაგვიკომენტაროს დომენი სადაც დაადეპლოვებს, ნეტლიფაის ნოტიფიკაციებში გითჰაბის ვებჰუკი უნდა მივაბათ...

<img src="http://www.picz.ge/img/s2/1904/23/d/d93b0ae58d2d.png"/>

**Comment by thecotne** [comment]
@shavidzet done!
