### ISSUE TITLE
Let's write zero-css

### ISSUE THREAD

**Issue by shavidzet** [Girchi/girchi-com-ui#23]
scss კარგია და თუ რომელიმე css მეთოდოლიაგას მიყვებით კლასნეიმების საწერად ეგეც ასწორებს, მაგრამ ვფიქრობ, რომ რაც უფრო გაიზრდება აპლიკაციის ინტერფეისის სირთულე მით უფრო რთული შესანარჩუნებელი გახდება css, ასევე ვფიქრობ რომ html და css ფაილებს შორის ნავიგაცია იწვევს ყურადღების გაფანტვას...

გირჩევთ, რომ გამოიყენოთ <a href="https://acss.io/">atomic css</a>, რომელიც საშუალებას მისცემს კონტრიბუტორებს დაიკიდონ css და აასწრაფონ დეველოპმენტი.
იდეა მარტივია, პროექტში ხდება atomizer-ის ინტეგრაცია, რომელიც უყურებს html ელემენტებს და კლასნეიმების მიხედვით აგენერირებს 1 css property-ზე ორიენტირებულ უტილიტა კლასებს.
რესპონსივიც მარტივია და ფსეუდო კლასებთან მუშაობაც.

რაც ყველზე მაგარია:
* css ფაილი ზომაში ძალიან პატარა გამოდის, რადგან reusability ხდება ერთი და იგივე კლასების.
* ერთი ფიჩერის დაფიქსვით წინას ვერ გააფუჭებ
* კომპონენტების დუბლირებაც მარტივია, რადგან შენს html-ს თან აქვს სტილთან საჭირო ყველა სამუშაო კლასი და დამატებითი css-ის კოპირება არ გიწევს
* single-oriented classების გატესტვა ბევრად უფრო მარტივია, რაც ამარტივებს ასევე e2e ტესტირებას.
მეტი პლიუსი არ მახსენდება მგონი 🤔 
* პროდაქშენში მკვდარი css აღარ არსებობს

**Comment by thecotne** [comment]
ეს ცოტა სადავო თემაა მე პირადად არ მომწონს css ის არ წერის ეს მიდგომა ...

თავისთავად რაღაცეებს აუმჯობესებს მაგრამ ჩემი აზრით უფრო მეტი მინუსი აქვს ამ მიდგომას ვიდრე პლიუსი

**Comment by shavidzet** [comment]
@thecotne ჩამოყარე მინუსები და ვიდავოთ 😎

**Comment by otarza** [comment]
@thecotne @shavidzet აქ არ იდაოთ გეხვეწებით, მეილებით დავისპამოთ უნდა მთელი dev გუნდი, ეს მართლა სადაო თემაა და სადმე FB ჯგუფში განიხილეთ თუ გინდათ.

ამ ეტაპზე Bootstrap ავირჩიეთ რადგან ბევრმა იცის და რომ დაგვჭირდეს სხვა დეველოპერების დახმარება დავიხმარებთ. 

უტილიტა კლასებსაც რაღაც დოზით გამოვიყენებთ.

**Comment by thecotne** [comment]
მორჩა კინო
