### ISSUE TITLE
მერჯის სტრატეგია

### ISSUE THREAD

**Issue by thecotne** [Girchi/girchi-com-ui#28]
- squash merging საშინელებაა ესეთ რაღაცეებს აკეთებს https://github.com/Girchi/girchi-com-ui/commit/29f1966537ad32400bef686c36c2fd856407b36e
- rebase merging ნორმალურია
- merge commits ესეც ნორმალურია (მაგრამ ბრენჩების შედარებისას ზედმეტი კომიტები იჩითება მერე და up to date ბრენჩების HEAD აღარ ემთხვევა ერთმანეთს)
- fast forward merge ყველაზე კაი რამეა მარა ეგ github ს არ აქვს 😢

თქვენის ნებართვით გავთიშავ rebase merging ებს და master ს დავარესეტებ develop ის HEAD ზე (რო git history ში არ იყოს ის კომიტი რომელიც არის 20 კომიტის სქვეშის შედეგი)

მერჯ კომიტებზე რავი თუ გინდათ იყოს თუ გინდათ გავთიშოთ

**Comment by thecotne** [comment]
cc @otarza @jibla @shavidzet

**Comment by shavidzet** [comment]
`squash merging`-ში რა არ მოგწონს, ბრენჩის კომიტება დაკომპრესდება 1 კომიტად და კომიტში PR-საც დალინკავს, მერე ვისაც უნდა გადავა ძველ პიარში და ბრენჩზე როგორ მიდიოდა მუშაობა იქ ნახავს.

მგონი რო code review-საც არ უშლის ეგ ხელს

**Comment by thecotne** [comment]
develop ის 20 კომიტი master ზე 1 კომიტად ჩანს მეტს რას უნდა ვერჩოდე ...

**Comment by thecotne** [comment]
fast forward merge ს პონტი ყოფილა github ზე შეგიძლია რომ up to date ობა მოითხოვო და მარტო რებეისით დამერჯო და გამოდის fast forward merge

**Comment by thecotne** [comment]
კაროჩე რებეის მერჯი დავტოვე მარტო და არავის პრეტენზია არ აქვს და ვტოვებ ესე

მასტერს ვააფდეითებ რო დასკვეშილი კომიტები არ იყოს #39
