### ISSUE TITLE
პარტიული სიის პროცენტების ველის გადაკეთება

### ISSUE THREAD

**Issue by IliaNoz** [Girchi/girchi-com-ui#48]
# კონტექსტი
გასაუმჯობესებლია პროცენტების ველის UX
![image](https://user-images.githubusercontent.com/17799522/58405224-00d68380-8078-11e9-983b-111c895f3121.png)

## ტექნიკური დავალება
უკვე დამატებული პოლიტიკოსის პროცენტი უნდა იყოს რედაქტირებადი.
მარტივი იქნებოდა `span` ელემნტი შევცავალოთ `input` ელემენტით და `input` ელემენტი გავსტილოთ ისე როგორც სპანი, თუ focused არ არის.

**Comment by Babunashvili** [comment]
ქვემოთ რომ არი ეგ ინფუთი არ გვაწყობს?
