### ISSUE TITLE
Configure Bootstrap according to the Styleguide

### ISSUE THREAD

**Issue by david-babunashvili** [Girchi/girchi-com-ui#5]

**Comment by thecotne** [comment]
Styleguide იც გალინკეთ (რა ფორმატშია?)

cc @otarza

**Comment by david-babunashvili** [comment]
> Styleguide იც გალინკეთ (რა ფორმატშია?)
> 
> cc @otarza

zeplin-ზეა

**Comment by thecotne** [comment]
@david-babunashvili zeplin ში ხო არ იხატება დიზაინები მე როგორც ვიცი და ამათგან ერთერთში უნდა იყოს დახატული  Sketch, Adobe XD CC, Figma, Photoshop 
და მაგის გაზიარება მგონი საკმარისი იქნება

**Comment by david-babunashvili** [comment]
> @david-babunashvili zeplin ში ხო არ იხატება დიზაინები მე როგორც ვიცი და ამათგან ერთერთში უნდა იყოს დახატული Sketch, Adobe XD CC, Figma, Photoshop
> და მაგის გაზიარება მგონი საკმარისი იქნება

მე როგორც ვიცი სტაილ გაიდი როგორც ასეთი მაგ: https://proxy.duckduckgo.com/iu/?u=https%3A%2F%2Fbashooka.com%2Fwp-content%2Fuploads%2F2016%2F11%2Fui-style-guide-examples-37.jpg&f=1 არ არი დახატული. უბრალოდ ზეპლინს აქ ეგ ფიჩერი რო პიდაპირ დიზიანიდან შეგიძლია ამოკრიბო ფერები კომპონენტები და ა.შ და ააწყო სტაილგაიდი ზეპლინზე.

**Comment by david-babunashvili** [comment]
თუმცა ჯერჯერობით მარტო ფერები გვაქ და რაღაცეები ჩემით ვიჩალიჩე ამოვიღე ზომები და სფეისინგები დიზიანიდან და გავწერე variables-ში

**Comment by david-babunashvili** [comment]
@thecotne ერთი პრობლემა მაქ ფონტზე და ვერაფერი მოვუხერხე და იქნებ შენ მირჩიო რამე FiraGO არის ფონტი ხოდა დიზაინში ტექსტები არი caps, ფოტოშოპშიც ვნახე ეს ფონტი და იქ ჩვეულებრივად გადაყავს caps-ში და ვებში ვერაფერი მოვუხერხე იმენა ქართულ ასოებზე არ მუშაობს caps-სი :/ 

http://prntscr.com/nb6fia http://prntscr.com/nb6fxt

**Comment by thecotne** [comment]
ეგ ფონტი როგორც ჩანს შეიცავს ქართულ uppercase სიმბოლოებს მაგრამ chrome ში და safari ში გადავამოწმე და არცერთში არ გამოაქ ეგ სიმბოლოები ბრაუზერს

ადრე დანერგეს მერე მიხვდნენ რო ეგეთი ფონტი კომპში არავის არ ეყენა და ყველა საიტს რო დედა ეტირა ისევ დააბრუნეს როგორც იყო

ამისი გამოსავალი არის მარტო ერთი უნდა იყოს ფონტი `FiraGO mtavruli` რომელიც ქართულ სიმბოლოებს გამოიტანს მთავრულად იმის მიუხედავად რომ უნიკოდის მიხედვით დაბალი რეგისტრის სიმბოლოები იქნება ტექსტი

---

related issue on chrome: https://bugs.chromium.org/p/chromium/issues/detail?id=865427

**Comment by thecotne** [comment]
დიზაინი მანახეთ რა მაინტერესებს

მწვანე ფონზე სტაფილოსფერი ღილაკი თეთრი ტექსტით მართლა არის დიზაინში?

![მწვანე ფონზე სტაფილოსფერი ღილაკი თეთრი ტექსტით](https://image.prntscr.com/image/YD-qxsYqSyWyxDtP9276lw.png)

**Comment by david-babunashvili** [comment]
email მომე აბა დაგაინვაითებ

**Comment by otarza** [comment]
@thecotne კი ეგეთი ვიზუალი გვაქვს, არ არის ცუდი სხვათაშორის :) 

მინდა ფაბლიქი გავხადო ზეპლინის პროექტი და ჯერ ვერ მოვახერხე, მგონი არ მაქ საკნარისი წვდომა, დიზაინერს ვთხოვე ეხლა და ვნახოთ აბა.

**Comment by otarza** [comment]
@thecotne წესით ფაბლიქია ამ ლინკით: https://scene.zeplin.io/project/5c9a22ea69aa0a0575fc055f

**Comment by thecotne** [comment]
ძაან კი გამიკვირდა მაგრამ "მწვანე ფონზე სტაფილოსფერი ღილაკი თეთრი ტექსტით" კარგად გამოიყურება მთლიან დიზაინში

---

<img width="392" alt="Screenshot 2019-04-12 23 59 40" src="https://user-images.githubusercontent.com/1606993/56062945-0d7c7200-5d7f-11e9-94d6-746ace6320cb.png">
