### ISSUE TITLE
ციტატების სტილის შესწორება

### ISSUE THREAD

**Issue by otarza** [Girchi/girchi-com-ui#51]
ციტატები სტილი არის justified როგორც ჩანს და მობაილზე ჩანს ცუდად, იხ. სურათი: 
![Screenshot from 2019-05-30 14-05-36](https://user-images.githubusercontent.com/1330491/58625765-32538700-82e4-11e9-893c-fe1d74506742.png)

**Comment by Babunashvili** [comment]
@otarza როგორ გავასწორო ედიტორიდან არის ეგ დადებული. ბლოკქუოთის შიგნით არის პარაგრაფი და აქვს გაწერილი რომ justified იყოს. მე არ მაქვს გაწერილი სტილებში ეგ. თუ თავისით ამატებს მაგას მაშინ დავაოვერრაიდებ მაგის სტილებს.

**Comment by otarza** [comment]
@david-babunashvili არა ჩვენი ქონთენთის ბრალი თუა ჩვენ გავასწორებთ. სორი. 

იყოს ეს ტასკი გახსნილი და რომ გავასწორებინებ მერე დავხურავ.

მადლობა.

**Comment by jibla** [comment]
ამას ვხურავ, გადავამოწმე და ქონთენთის ბრალია. ხელით აქვთ მითითებული justify.

**Comment by jibla** [comment]
აა, sorry, @otarza ახლა წავიკითხე შენი კომენტარი. :)
